[workspace]
members=["base", "collection", "lifecycle", "match_util", "pub_lib"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Evan.Pan"]
edition = "2024"

[workspace.dependencies]
match_util = {package = "match_util", version = "0.1.0"}
