[package]
name = "base"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
match_util = { path = "../match_util", version = "0.1.0" }
pub_lib = { path = "../pub_lib", version = "0.1.0" }
analyzer = { path = "../analyzer", version = "0.1.0" }